apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.0
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always