apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - image: consul:1.6
          name: consul
          ports:
            - containerPort: 8500
          resources: {}
      restartPolicy: Always