apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
    - image: gcr.io/containers-java/sbms-jib
      jib: {}
deploy:
  kubectl:
    manifests :
      - k8s/*.yaml
#  helm:
#    releases:
#      - name: spring-boot-jib
#        chartPath: helm
#        values:
#          image.repository: gcr.io/containers-java/sbms-jib
#        setValues:
#          image.tag: ""
