apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: gcr.io/containers-java/frontend
          name: frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always