apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - env:
        - name: NEO4J_AUTH
          value: none
        image: neo4j
        name: neo4j
        ports:
        - containerPort: 7687
        - containerPort: 7474
        resources: {}
      restartPolicy: Always