apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:4.2
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always